In [2]:
import numpy as np

# sorting

In [10]:
a = np.array([20,32,5,30,10])

In [11]:
a

array([20, 32,  5, 30, 10])

In [12]:
np.sort(a) # burada a yı sıralar ama güncellemez

array([ 5, 10, 20, 30, 32])

In [13]:
a

array([20, 32,  5, 30, 10])

In [14]:
a.sort() # a' yı sıralar ve günceller

In [15]:
a # güncel a

array([ 5, 10, 20, 30, 32])

#Argsort

In [16]:
a = np.array([3,1,6,5,4,2])

In [17]:
# küçükten büyüpe sıralar elemanların indexsini verir
idxs = np.argsort(a)

In [18]:
idxs

array([1, 5, 0, 4, 3, 2])

In [19]:
a.argsort()

array([1, 5, 0, 4, 3, 2])

In [20]:
a

array([3, 1, 6, 5, 4, 2])