In [4]:
import numpy as np

In [5]:
a= [1,2,3]
b=[2,4,8]

a*b 

# işlemler listelerde tanımlı değil o yüzdwen hata verir.

TypeError: ignored

In [6]:
[2,4,8] * 3

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [7]:
x=np.array([1,2,3])
y=np.array([2,4,8])

x*y

# aynı sayoda elemanları olması gerekiyor

array([ 2,  8, 24])

In [8]:
x2=np.array([1,2,3])
y2=np.array([2,4,8,9])

x2 * y2

ValueError: ignored

In [9]:
a= [1,2,3]
b=[2,4,8]

In [10]:
a + b

[1, 2, 3, 2, 4, 8]

In [11]:
print(x)
print(y)

[1 2 3]
[2 4 8]


In [12]:
x + y

array([ 3,  6, 11])

In [13]:
x

array([1, 2, 3])

In [15]:
3 * x

array([3, 6, 9])

In [16]:
x = x * 3

In [17]:
x

array([3, 6, 9])

In [18]:
np.array([3,5,9])*3

array([ 9, 15, 27])