In [1]:
import numpy as np

In [5]:
np.random.normal(0,1,(4,5)) #ortalamsı 0 ve standart sapması 1 olan 4 e 5 bir matris

array([[-1.70510814,  1.71332748,  0.81834976,  0.7319973 , -1.09318341],
       [-0.53353646,  0.58793691, -0.76827118,  0.63362863,  1.13435963],
       [ 1.71861374,  0.24742958,  0.13858137, -0.50535128,  0.64684178],
       [ 0.01227354, -0.06629461, -1.24159479,  0.97417624,  0.04905719]])

In [6]:
np.random.normal(0,100, (4,5))

array([[ 108.99046855,   10.31030111,   14.4621203 , -160.72335563,
          63.80242535],
       [ -22.16114147, -182.62225026,   62.42459602,  -37.0027513 ,
        -153.46296807],
       [ -52.80797418,   40.35156588, -139.39514827,    5.90756728,
          39.75482529],
       [ -27.61944925,  128.85576972,    6.68880005, -108.65904902,
          67.7969754 ]])

In [7]:
np.random.normal(10,100, (4,5))

array([[ -52.06013352, -136.6226168 ,  -51.81440771,   31.08139242,
          -7.05657297],
       [ 148.61258658,  111.58850076,  103.55768427,  151.65716455,
        -146.50626917],
       [ 157.01514621, -156.00701241,   44.54013257, -105.07642897,
         114.46051498],
       [ 129.42672278,  170.00423814,  185.36748351,  -66.0553466 ,
         -80.49172743]])

In [ ]:
np.random.normal(10,1, (4,5))