In [1]:
import numpy as np

# belirtilen bir elemandan array oluşturmak

In [3]:
np.full((4,5), 5) #sadec 5 lerden oluşan bir array oluşturur

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [4]:
np.full(4,5,5) # hata verir.

TypeError: ignored

In [5]:
np.full(4,5) # 4 elemanlı 5 lerden oluşan array

array([5, 5, 5, 5])

In [9]:
np.full((4,5), 5.2, dtype= str) # integer a çevirip strin olarak yazar

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

In [10]:
np.full((4,5), "5.2")

array([['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2']], dtype='<U3')

# Ardaşık sayılardan array oluşturmak

In [15]:
np.arange(0,12) # 0 dan 12 kadar olan sayılardan oluşan bir array oluşturur. 12 dahi depğil

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
np.arange(2,12,2) # 2 den 12' e 2 artarak gider.

array([ 2,  4,  6,  8, 10])

In [11]:
np.arange(2,12,-2) # 2 den 12,e -2 olarak gidemediği için boş araray oluşturur.

array([], dtype=int64)

In [12]:
np.arange(12,2,-2) #12'den 2'e -2 azalarak gider

array([12, 10,  8,  6,  4])