In [1]:
import numpy as np

## reshaping

In [2]:
a= np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a.ndim

1

In [4]:
a.size

10

In [5]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [7]:
a.reshape(2,5).ndim

2

In [8]:
a.reshape(6,2) # eleman sayısı tutmaz ise hata alırım

ValueError: ignored

# - 1 ile boyuta karar vermek 

In [10]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## yeni boyut eklemek

In [11]:
a=np.arange(1,11)

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a.ndim

1

In [13]:
a[np.newaxis, :].ndim

2

In [14]:
a[np.newaxis, :].shape

(1, 10)

In [ ]:
a[:,np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [20]:
a[:,np.newaxis].shape

(10, 1)

In [16]:
a[None, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [17]:
a[None, :].shape

(1, 10)

In [18]:
a[:,None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [19]:
a[:, None].shape

(10, 1)

In [ ]:
a=np.arange(1,7)
x=a[np.newaxis,:] 

x.shape

(1, 6)