## Stack




*   Stack mantığı yeni dimension(boyut) ekleyip o dimension üzerinde concatenetion yapatrak da sağlayabiliriz.







## stack

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])

In [3]:
b=np.array([5,6,7,8])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b

array([5, 6, 7, 8])

In [6]:
a.shape

(4,)

In [7]:
b.shape

(4,)

In [8]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
np.stack([a,b], axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## vstack