In [1]:
import numpy as np

In [2]:
x=np.array([1,2,2,4.6]) # hepsi floata döner

In [3]:
x

array([1. , 2. , 2. , 4.6])

In [20]:
x=np.array([1,2,2,4.6], dtype="int32") 

# dtype kullanark istediğimiz veri tipine dönüşüm sağlayabiliriz. 

In [21]:
x

array([1, 2, 2, 4], dtype=int32)

In [23]:
x=np.array([1,2,2,4.6], dtype="str") #hepsi stringe dönüşecek

In [24]:
x

array(['1', '2', '2', '4.6'], dtype='<U3')

In [25]:
x=np.array(["a"], dtype="int32") 

# a nın integer gösterimi olmadığı için hata verir.

ValueError: ignored

In [26]:
x=np.array(["5"], dtype="int32") 
# burda string olan ifadenin integer karşılığı olduğu için hata vermez 

In [31]:
x

array([5], dtype=int32)

In [30]:
x=np.array(["4.2"] ,dtype="int32") # array'inin elemanı hangi veri tipine cast olur?

ValueError: ignored