In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4])

In [ ]:
b=np.array([5,6,7,8])

In [ ]:
# a ve b güncellenmez
np.concatenate([a,b]) # birleştirme yapar

array([ 6,  8, 10, 12,  1,  2,  3,  4])

In [ ]:
# python listelerinide concatanate ile birleştirebiliriz

l=[9,10]

In [ ]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
l=[9,10,11.2]

In [ ]:
np.concatenate([a,b,l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. , 11.2])

In [ ]:
l=[9,10,"11.2"]

In [ ]:
np.concatenate([a,b,l])

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11.2'],
      dtype='<U21')

In [ ]:
l=(9,10) # tuple da verebiliriz

In [ ]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Size Mismatch


In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
x=np.array([[1,2,3],
            [4,5,6]])

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x.size

6

In [ ]:
x.shape

(2, 3)

In [ ]:
a.shape

(4,)

In [ ]:
# shape mismatch
np.concatenate([x,a])

ValueError: ignored

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([x,x], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])