In [1]:
import numpy as np

## spliting

In [7]:
l = [10,20,30,40,50,60,70,80]

In [6]:
l

[10, 20, 30, 40, 50, 60, 70, 80]

In [4]:
np.split(l,[2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [8]:
a=np.array([10,20,30,40,50,60,70,80])

In [9]:
np.split(a,[2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [10]:
np.split(l,[3,5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]

In [18]:
type(np.split(l,[3,5]))

list

## Split'in sonucunu birden çok değişkene eşitleme

In [14]:
a, b = (1,10)    

In [15]:
print(a)
print(b)

1
10


In [16]:
x,y,z=np.split(l, [2,6])

In [17]:
print(x)
print(y)
print(z)

[10 20]
[30 40 50 60]
[70 80]


## Vsplit

In [19]:
a = np.arange(20).reshape(2,10)

In [20]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [21]:
np.vsplit(a, [1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [22]:
np.vsplit(a, [1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [23]:
np.vsplit(a, [2])

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([], shape=(0, 10), dtype=int64)]

In [41]:
a = np.arange(20).reshape(5,4)

In [42]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [45]:
np.vsplit(a,[1,3])

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [46]:
x, y, z = np.vsplit(a,[1,3])

In [47]:
x

array([[0, 1, 2, 3]])

In [48]:
y

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
z

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

# hsplit

In [24]:
a = np.arange(20).reshape(2,10)

In [25]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [26]:
np.hsplit(a, [2])

[array([[ 0,  1],
        [10, 11]]), array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [27]:
np.hsplit(a, [2])[0]

array([[ 0,  1],
       [10, 11]])

In [28]:
np.hsplit(a, [2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [29]:
np.hsplit(a, [2])[0].shape

(2, 2)

In [30]:
np.hsplit(a, [2])[1].shape

(2, 8)

In [31]:
x, y = np.hsplit(a, [2])

In [34]:
print(x)

[[ 0  1]
 [10 11]]


In [35]:
print(y)

[[ 2  3  4  5  6  7  8  9]
 [12 13 14 15 16 17 18 19]]


In [36]:
x, y, z = np.hsplit(a, [2,4])

In [37]:
x

array([[ 0,  1],
       [10, 11]])

In [39]:
y

array([[ 2,  3],
       [12, 13]])

In [40]:
z

array([[ 4,  5,  6,  7,  8,  9],
       [14, 15, 16, 17, 18, 19]])