In [1]:
import numpy as np

## Shape

In [2]:
x= np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
y= np.zeros((2,5,4))
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [4]:
x.shape

(2, 3)

In [5]:
y.shape

(2, 5, 4)

## Ndim

In [6]:
x= np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
y= np.zeros((2,5,4))
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [8]:
x.ndim

2

In [9]:
y.ndim

3

## size

In [10]:
x= np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
y= np.zeros((2,5,4))

print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
x.size

6

In [ ]:
y.size

40

## dtype

In [ ]:
x= np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
x.dtype

dtype('float64')